# Generated by Django 5.2.5 on 2025-09-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('cnpj', models.IntegerField()),
                ('endereco', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('complemento', models.CharField(max_length=200)),
                ('data_nascimento', models.IntegerField()),
                ('cidade', models.CharField(max_length=200)),
                ('uf', models.CharField(max_length=2)),
                ('cep', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
            ],
        ),
    ]
