# Generated by Django 5.2.5 on 2025-09-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cep',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='complemento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email',
            field=models.EmailField(max_length=200),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
