# Generated by Django 5.2.5 on 2025-09-23 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_orcamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='data_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.CharField(choices=[('Unidades', 'Unidades'), ('Caixa', 'Caixa')], default='Unidades', max_length=50),
        ),
    ]
