# Generated by Django 5.2.5 on 2025-09-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=200)),
                ('descreva', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateField(),
        ),
    ]
