# Generated by Django 5.2.5 on 2025-09-24 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_suporte_alter_orcamento_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='data',
            field=models.DateField(auto_now_add=True),
        ),
    ]
