# Generated by Django 5.2.5 on 2025-09-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_produto_quantidade_alter_produto_nome'),
        ('app', '0008_alter_orcamento_data'),
    ]

    operations = [
    ]
