# Generated by Django 5.2.5 on 2025-10-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_produto_fornecedor_alter_produto_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
