# Generated by Django 5.2.5 on 2025-10-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_orcamento_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='itens_quantidades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='itens_valores',
            field=models.TextField(blank=True, null=True),
        ),
    ]
