# Generated by Django 5.2.6 on 2025-10-09 14:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('codigo', models.CharField(max_length=6)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('usado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
