# Generated by Django 5.2.6 on 2025-10-10 15:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_recuperacaosenha'),
    ]

    operations = [
        migrations.AddField(
            model_name='suporte',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
