# Generated by Django 5.2.6 on 2025-10-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_suporte_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
