# Generated by Django 5.2.6 on 2025-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_fornecedor_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='observacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
