# Generated by Django 5.2.6 on 2025-10-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_produto_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='itens_unidades',
            field=models.TextField(blank=True, null=True),
        ),
    ]
