# Generated by Django 5.2.6 on 2025-10-17 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_orcamento_itens_unidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='validade',
            field=models.DateField(blank=True, null=True),
        ),
    ]
