# Generated by Django 5.2.6 on 2025-10-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_merge_0019_usuario_is_admin_0023_orcamento_desconto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='is_admin',
        ),
    ]
