# Generated by Django 5.2.6 on 2025-10-17 20:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_usuario_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo_barras', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('unidade', models.CharField(choices=[('Diário', 'Diário'), ('Mensal', 'Mensal'), ('Anual', 'Anual')], default='Diário', max_length=50)),
                ('quantidade', models.IntegerField(default=1)),
                ('validade', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='app.fornecedor')),
            ],
        ),
    ]
