# Generated by Django 5.2.6 on 2025-10-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
