# Generated by Django 5.2.6 on 2025-10-21 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_orcamento_uf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamento',
            name='uf',
        ),
    ]
