# Generated by Django 5.2.6 on 2025-10-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_remove_orcamento_uf'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
