# Generated by Django 5.2.6 on 2025-11-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_produto_preco_compra_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='unidade',
            field=models.CharField(choices=[('Hora', 'Hora'), ('Semana', 'Semana'), ('Mês', 'Mês'), ('Ano', 'Ano'), ('Serviço', 'Serviço')], default='Hora', max_length=50),
        ),
    ]
