# Generated by Django 5.2.6 on 2025-11-10 14:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_movimentacaoestoque_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamento',
            name='data_hora_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.usuario'),
        ),
    ]
