# Generated by Django 5.2.6 on 2025-11-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_orcamento_data_hora_criacao_orcamento_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
